import Link from 'next/link';
import { ArrowRight, Building2, CheckCircle2, Clock3, Globe2, MessageCircle, Plane, Quote, ShieldCheck } from 'lucide-react';
import { BrochureGrid } from '@/components/brochure-grid';
import { services, testimonials } from '@/lib/content';
import { whatsappUrl } from '@/lib/site';

export default function HomePage() {
  return <>
    <section className="hero-grid overflow-hidden bg-[#07131f] text-white">
      <div className="shell grid min-h-[720px] gap-12 py-16 lg:grid-cols-[1.15fr_.85fr] lg:items-center lg:py-20">
        <div><span className="eyebrow text-[#d8b86f]">Travel & Land Arrangement • Saudi • Mesir • Turki</span><h1 className="serif mt-6 max-w-4xl text-balance text-[clamp(3.6rem,8vw,7.7rem)] font-semibold leading-[.82] text-[#f4ead7]">Travel operations,<br/><em className="font-normal text-[#c6a25a]">without the noise.</em></h1><p className="mt-7 max-w-xl text-base leading-8 text-white/55 sm:text-lg">Satu pintu untuk kebutuhan Land Arrangement, visa, tiket, transport, Haramain, dan bagasi Cairo ⇄ Jakarta—dengan brief yang jelas sebelum masuk WhatsApp.</p><div className="mt-9 flex flex-wrap gap-3"><a href={whatsappUrl("Assalamu'alaikum Barokah Group, saya ingin konsultasi layanan. Kebutuhan saya: ...")} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full bg-[#c6a25a] px-5 py-3 text-sm font-black text-[#07131f] transition hover:bg-[#d9bd7c]"><MessageCircle size={18}/> Konsultasi WhatsApp</a><Link href="/b2b" className="inline-flex items-center gap-2 rounded-full border border-white/15 px-5 py-3 text-sm font-bold text-white/75 transition hover:border-[#c6a25a]/50 hover:text-white">Brief kebutuhan B2B <ArrowRight size={16}/></Link></div><div className="mt-14 grid max-w-2xl grid-cols-3 border-y border-white/10 py-5"><div><p className="text-2xl font-black text-[#d8b86f]">3</p><p className="mt-1 text-[10px] uppercase tracking-widest text-white/35">Country Hubs</p></div><div><p className="text-2xl font-black text-[#d8b86f]">B2B</p><p className="mt-1 text-[10px] uppercase tracking-widest text-white/35">Travel Ready</p></div><div><p className="text-2xl font-black text-[#d8b86f]">1:1</p><p className="mt-1 text-[10px] uppercase tracking-widest text-white/35">Admin Review</p></div></div></div>
        <div className="relative hidden min-h-[520px] lg:block"><div className="absolute right-0 top-8 h-[440px] w-[78%] border border-[#c6a25a]/25"></div><div className="absolute bottom-2 left-0 w-[82%] bg-[#f2eadb] p-8 text-[#07131f] shadow-2xl"><span className="eyebrow text-[#9d7b3e]">Operational desk</span><h2 className="serif mt-4 text-4xl font-semibold">Brief → Review → Confirm</h2><div className="mt-8 space-y-5">{[['01','Kirim kebutuhan'],['02','Admin review scope'],['03','Konfirmasi detail & next step']].map(([n,t])=><div key={n} className="flex items-center gap-4 border-b border-black/10 pb-4"><span className="text-xs font-black text-[#a7803d]">{n}</span><span className="text-sm font-black">{t}</span></div>)}</div></div></div>
      </div>
    </section>

    <div className="marquee border-b border-[#07131f]/10 bg-[#c6a25a] py-3 text-[10px] font-black uppercase tracking-[.22em]"><div className="marquee-track"><span className="px-7">Land Arrangement Umrah</span><span className="px-7">Visa Umrah & Mesir</span><span className="px-7">Haramain Train</span><span className="px-7">NWBus</span><span className="px-7">Bagasi Cairo ⇄ Jakarta</span><span className="px-7">B2B Travel Agent</span><span className="px-7">Land Arrangement Umrah</span><span className="px-7">Visa Umrah & Mesir</span><span className="px-7">Haramain Train</span><span className="px-7">NWBus</span><span className="px-7">Bagasi Cairo ⇄ Jakarta</span><span className="px-7">B2B Travel Agent</span></div></div>

    <section className="section"><div className="shell grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><span className="eyebrow text-[#9f7d3d]">Service directory</span><h2 className="serif mt-4 text-balance text-5xl font-semibold">Semua kebutuhan inti, dalam satu struktur.</h2><p className="mt-5 max-w-sm text-sm leading-7 text-slate-500">Pilih layanan untuk melihat scope, lalu lanjutkan dengan brief yang spesifik.</p></div><div className="border-t border-[#07131f]/15">{services.slice(0,6).map((service,i)=>{const Icon=service.icon;return <Link key={service.slug} href={`/layanan/${service.slug}`} className="service-row grid grid-cols-[42px_1fr_auto] items-center gap-4 border-b border-[#07131f]/15 py-5"><span className="text-[10px] font-black text-[#a7803d]">0{i+1}</span><div className="flex items-center gap-4"><Icon size={21} strokeWidth={1.6}/><div><h3 className="font-black">{service.title}</h3><p className="mt-1 hidden text-xs text-slate-500 sm:block">{service.summary}</p></div></div><ArrowRight size={18}/></Link>})}</div></div></section>

    <section className="bg-[#ded4c4] py-20"><div className="shell"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><span className="eyebrow text-[#8e6d36]">Brosur existing</span><h2 className="serif mt-3 text-5xl font-semibold">Visual asli tetap dipertahankan.</h2></div><Link href="/promo-brosur" className="inline-flex items-center gap-2 text-sm font-black">Lihat galeri <ArrowRight size={16}/></Link></div><div className="mt-9"><BrochureGrid compact/></div></div></section>

    <section className="section bg-[#07131f] text-white"><div className="shell grid gap-10 lg:grid-cols-[1fr_1fr]"><div><span className="eyebrow text-[#d6b66f]">B2B operating model</span><h2 className="serif mt-4 max-w-xl text-balance text-5xl font-semibold text-[#f3e8d4]">Dibuat untuk travel agent yang butuh jawaban operasional.</h2><p className="mt-6 max-w-lg text-sm leading-8 text-white/50">Brief group, kota, tanggal, pax, hotel, visa, transport, dan kebutuhan handling dapat dikumpulkan lebih rapi sebelum diskusi admin.</p><Link href="/b2b" className="mt-8 inline-flex items-center gap-2 rounded-full border border-[#c6a25a]/40 px-5 py-3 text-sm font-black text-[#d6b66f]">Buka B2B brief <ArrowRight size={16}/></Link></div><div className="grid gap-3 sm:grid-cols-2">{[[Building2,'Group handling'],[Plane,'Multi-country'],[Clock3,'Faster briefing'],[Globe2,'Cross-border']].map(([Icon,label])=><div key={String(label)} className="rounded-2xl border border-white/10 bg-white/[.035] p-6">{typeof Icon !== 'string' && <Icon size={25} className="text-[#c6a25a]"/>}<p className="mt-8 text-sm font-black">{String(label)}</p></div>)}</div></div></section>

    <section className="section"><div className="shell"><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><span className="eyebrow text-[#9f7d3d]">Why Barokah Group</span><h2 className="serif mt-4 text-5xl font-semibold">Clear scope before conversation.</h2></div><div className="grid gap-4 sm:grid-cols-3">{[[ShieldCheck,'Scope lebih jelas','Layanan dan batasannya ditampilkan sebelum chat.'],[CheckCircle2,'Brief lebih siap','Form membantu admin memahami kebutuhan lebih cepat.'],[Globe2,'Lintas negara','Saudi, Mesir, Turki, dan kebutuhan Indonesia terkait.']].map(([Icon,title,desc])=><div key={String(title)} className="card p-6">{typeof Icon !== 'string' && <Icon size={24} className="text-[#b58d47]"/>}<h3 className="mt-10 font-black">{String(title)}</h3><p className="mt-3 text-xs leading-6 text-slate-500">{String(desc)}</p></div>)}</div></div></div></section>

    <section className="border-y border-[#07131f]/10 bg-[#eee8dc] py-20"><div className="shell"><div className="max-w-2xl"><span className="eyebrow text-[#9f7d3d]">Placeholder testimonial layout</span><h2 className="serif mt-3 text-4xl font-semibold">Siap diisi social proof yang terverifikasi.</h2><p className="mt-4 text-sm leading-7 text-slate-500">Konten di bawah adalah demo layout, bukan testimoni pelanggan asli. Ganti dengan review nyata yang sudah mendapat izin publikasi.</p></div><div className="mt-8 grid gap-5 md:grid-cols-3">{testimonials.map(t=><article key={t.name} className="card bg-white/55 p-6"><Quote size={20} className="text-[#b58d47]"/><p className="mt-6 text-sm leading-7 text-slate-600">“{t.quote}”</p><div className="mt-8 border-t border-black/10 pt-4"><p className="text-xs font-black">{t.name}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-slate-400">{t.role}</p></div></article>)}</div></div></section>
  </>;
}
