'use client';
import { FormEvent, useState } from 'react';
import { Send } from 'lucide-react';
import { whatsappUrl } from '@/lib/site';

export function QuoteForm(){
  const [status,setStatus]=useState('');
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault(); const fd=new FormData(e.currentTarget); const name=String(fd.get('name')||'').trim(); const service=String(fd.get('service')||'').trim(); const pax=String(fd.get('pax')||'').trim(); const date=String(fd.get('date')||'').trim(); const note=String(fd.get('note')||'').trim(); if(!name||!service||!note){setStatus('Mohon isi nama, layanan, dan detail kebutuhan.');return;} const message=`Assalamu'alaikum Barokah Group, saya ingin request quote.\n\nNama: ${name}\nLayanan: ${service}\nPax: ${pax||'-'}\nTanggal/periode: ${date||'-'}\nDetail: ${note}`; window.open(whatsappUrl(message),'_blank','noopener,noreferrer'); setStatus('Brief siap. WhatsApp dibuka di tab baru.');}
  return <form onSubmit={submit} className="card bg-white/55 p-6 sm:p-8"><span className="eyebrow text-[#9f7d3d]">Request quote</span><h2 className="serif mt-3 text-3xl font-semibold">Kirim brief yang cukup untuk direview.</h2><div className="mt-7 grid gap-4 sm:grid-cols-2"><label className="text-xs font-black">Nama<input name="name" className="mt-2 w-full border border-black/15 bg-transparent px-4 py-3 font-normal outline-none focus:border-[#b58d47]" placeholder="Nama / nama travel"/></label><label className="text-xs font-black">Layanan<select name="service" className="mt-2 w-full border border-black/15 bg-transparent px-4 py-3 font-normal outline-none focus:border-[#b58d47]"><option value="">Pilih layanan</option><option>Land Arrangement Umrah</option><option>Land Arrangement Mesir</option><option>Land Arrangement Turki</option><option>Visa</option><option>Tiket / Transport</option><option>Bagasi Cairo-Jakarta</option></select></label><label className="text-xs font-black">Jumlah pax<input name="pax" className="mt-2 w-full border border-black/15 bg-transparent px-4 py-3 font-normal outline-none" placeholder="Contoh: 32 pax"/></label><label className="text-xs font-black">Tanggal / periode<input name="date" className="mt-2 w-full border border-black/15 bg-transparent px-4 py-3 font-normal outline-none" placeholder="Contoh: 12–20 Oktober"/></label></div><label className="mt-4 block text-xs font-black">Detail kebutuhan<textarea name="note" rows={5} className="mt-2 w-full resize-y border border-black/15 bg-transparent px-4 py-3 font-normal outline-none focus:border-[#b58d47]" placeholder="Kota, hotel, visa, transport, rute, atau catatan penting..."/></label><button className="mt-5 inline-flex items-center gap-2 rounded-full bg-[#07131f] px-5 py-3 text-sm font-black text-[#e0c27f]"><Send size={16}/> Buka brief di WhatsApp</button><p aria-live="polite" className="mt-3 text-xs text-slate-500">{status}</p></form>
}
