import type { Metadata } from 'next';
import { ArrowRight, Luggage, MessageCircle, PackageCheck, ShieldAlert } from 'lucide-react';
import { baggageSchedules } from '@/lib/content';
import { whatsappUrl } from '@/lib/site';

export const metadata: Metadata = { title: 'Bagasi Cairo ⇄ Jakarta', description: 'Konsultasi jadwal dan reservasi bagasi Cairo–Jakarta bersama Barokah Group.' };
export default function BaggagePage(){return <>
  <section className="bg-[#c6a25a] py-20"><div className="shell grid gap-10 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><span className="eyebrow opacity-60">Cairo ⇄ Jakarta</span><h1 className="serif mt-4 text-balance text-5xl font-semibold sm:text-6xl">Jalur bagasi untuk mahasiswa, diaspora, dan traveler.</h1><p className="mt-5 max-w-2xl text-base leading-8 opacity-70">Kirim estimasi berat dan jenis barang. Admin akan mengonfirmasi kloter, slot, serta ketentuan yang berlaku.</p><a href={whatsappUrl("Assalamu'alaikum Barokah Group, saya ingin tanya slot bagasi Cairo-Jakarta. Estimasi berat: ... kg. Jenis barang: ...")} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#07131f] px-5 py-3 text-sm font-black text-[#dfc186]"><MessageCircle size={18}/> Tanya slot bagasi</a></div><div className="grid place-items-center"><div className="grid size-64 place-items-center rounded-full border border-[#07131f]/20 bg-[#07131f] text-[#d6b66f] shadow-2xl"><Luggage size={92}/></div></div></div></section>
  <section className="section"><div className="shell"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><span className="eyebrow text-[#9f7d3d]">Schedule board</span><h2 className="serif mt-3 text-4xl font-semibold">Jadwal dikonfirmasi admin.</h2></div><p className="max-w-md text-xs leading-6 text-slate-500">Kami sengaja tidak menampilkan tanggal lama atau status “open” yang belum terverifikasi. Konten jadwal akan dibuat data-driven pada fase admin berikutnya.</p></div><div className="mt-8 grid gap-5 md:grid-cols-2">{baggageSchedules.map(item=><article key={item.route} className="card p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-widest text-[#9f7d3d]">{item.status}</p><h3 className="serif mt-2 text-3xl font-semibold">{item.route}</h3></div><PackageCheck className="text-[#b58d47]"/></div><p className="mt-5 text-sm font-black">{item.date}</p><p className="mt-2 text-sm leading-7 text-slate-500">{item.note}</p><a href={whatsappUrl(`Assalamu'alaikum Barokah Group, saya ingin tanya bagasi rute ${item.route}. Estimasi berat: ... kg. Jenis barang: ...`)} target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center gap-2 text-sm font-black">Konsultasi rute ini <ArrowRight size={16}/></a></article>)}</div></div></section>
  <section className="section bg-[#07131f] text-white"><div className="shell grid gap-6 md:grid-cols-2"><div className="rounded-3xl border border-white/10 bg-white/[.04] p-6"><PackageCheck className="text-[#c6a25a]"/><h3 className="serif mt-5 text-2xl font-semibold">Informasi yang perlu disiapkan</h3><p className="mt-3 text-sm leading-7 text-white/55">Rute, estimasi berat, jenis barang, jumlah koli, dan perkiraan waktu kebutuhan.</p></div><div className="rounded-3xl border border-white/10 bg-white/[.04] p-6"><ShieldAlert className="text-[#c6a25a]"/><h3 className="serif mt-5 text-2xl font-semibold">Barang perlu diverifikasi</h3><p className="mt-3 text-sm leading-7 text-white/55">Ketentuan barang mengikuti aturan penerbangan, kepabeanan, dan kebijakan operasional yang berlaku pada kloter terkait.</p></div></div></section>
</>}
