import type { Metadata } from 'next';
import { Luggage, MessageCircle, PackageCheck, ShieldAlert } from 'lucide-react';
import { BaggageScheduleBoard } from '@/components/baggage-schedule-board';
import { whatsappUrl } from '@/lib/site';

export const metadata: Metadata = { title: 'Bagasi Cairo ⇄ Jakarta', description: 'Jadwal, konsultasi, dan reservasi bagasi Cairo–Jakarta bersama Barokah Group.' };

export default function BaggagePage(){return <>
  <section className="bg-gradient-to-br from-[#dfbf72] via-[#c49a45] to-[#96721f] py-20"><div className="shell grid gap-10 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><span className="eyebrow text-[#07131f]/65">Cairo ⇄ Jakarta</span><h1 className="serif mt-4 text-balance text-5xl font-bold text-[#07131f] sm:text-6xl">Kirim bagasi lebih praktis dengan jadwal yang jelas.</h1><p className="mt-5 max-w-2xl text-base font-medium leading-8 text-[#07131f]/70">Layanan bagasi untuk mahasiswa, diaspora, traveler, dan kebutuhan personal dari Cairo ke Jakarta maupun sebaliknya.</p><a href={whatsappUrl("Assalamu'alaikum Barokah Group, saya ingin reservasi bagasi Cairo-Jakarta. Estimasi berat: ... kg. Jenis barang: ...")} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-[#07131f] px-5 py-3 text-sm font-black text-[#dfbf72] shadow-xl"><MessageCircle size={18}/> Reservasi Bagasi</a></div><div className="grid place-items-center"><div className="grid size-64 place-items-center rounded-full border border-[#07131f]/20 bg-[#07131f] text-[#d3ab5a] shadow-2xl"><Luggage size={92}/></div></div></div></section>
  <section className="section"><div className="shell"><div className="mb-8 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><span className="eyebrow text-[#96721f]">Jadwal Keberangkatan</span><h2 className="serif mt-3 text-4xl font-bold text-[#07131f]">Pilih kloter yang sesuai.</h2></div><p className="max-w-md text-xs leading-6 text-slate-500">Jadwal dan status slot diperbarui langsung oleh admin Barokah Group.</p></div><BaggageScheduleBoard /></div></section>
  <section className="section bg-[#07131f] text-white"><div className="shell grid gap-6 md:grid-cols-2"><div className="rounded-3xl border border-[#b8903a]/25 bg-white/[.04] p-6"><PackageCheck className="text-[#d3ab5a]"/><h3 className="serif mt-5 text-2xl font-bold text-[#f5e9c8]">Siapkan detail pengiriman</h3><p className="mt-3 text-sm leading-7 text-white/55">Rute, estimasi berat, jenis barang, jumlah koli, dan jadwal yang dipilih.</p></div><div className="rounded-3xl border border-[#b8903a]/25 bg-white/[.04] p-6"><ShieldAlert className="text-[#d3ab5a]"/><h3 className="serif mt-5 text-2xl font-bold text-[#f5e9c8]">Aman & terkoordinasi</h3><p className="mt-3 text-sm leading-7 text-white/55">Admin membantu pengecekan ketentuan barang dan detail operasional sebelum pengiriman.</p></div></div></section>
</>}
